from . import region
from . import post_office_status
from . import postal_dispatch
from . import res_country_state
from . import branch
from . import loan_location
from . import product_class
from . import writeoff
from . import law_firm
from . import notification_template
from . import res_users
from . import product_template
from . import account_move
from . import arbitration_billing
from . import ir_actions_report
from . import bharat_arbitrator_blockout
from . import loan_stage
from . import loan_milestone
from . import res_company
from . import loan
