{
    'name': 'BharatNyay Core',
    'version': '18.0.31.0.37',
    'icon': '/bharatnyay_core/static/description/icon.png',
    'summary': 'Loan portfolio aligned to Excel import template',
    'description': """
        Loan sheet model (`bharat.loan`) with masters for region, state, branch, location,
        product class, write-off and law firm. Import from spreadsheet via List ▸ Favorites ▸ Import Records.
    """,
    'category': 'Operations/Disputes',
    'author': 'BharatNyay Team',
    'depends': ['web', 'mail', 'account', 'account_payment', 'spiffy_theme_backend'],
    'data': [
        'security/bharatnyay_groups.xml',
        'security/bharatnyay_record_rules.xml',
        'security/ir.model.access.csv',
        'data/loan_sequence_data.xml',
        'data/loan_stage_data.xml',
        'data/loan_stage_award_update.xml',
        'data/loan_milestone_data.xml',
        'data/notification_template_data.xml',
        'views/master_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/notification_template_views.xml',
        'views/loan_notice_wizard_views.xml',
        'views/loan_notice_response_wizard_views.xml',
        'views/bharat_operational_views.xml',
        'views/bharat_account_product_views.xml',
        'views/loan_hearing_wizard_views.xml',
        'views/loan_award_wizard_views.xml',
        'views/loan_assign_arbitrator_wizard_views.xml',
        'views/hearing_line_views.xml',
        'views/interim_order_views.xml',
        'data/bharat_report_paperformat.xml',
        'reports/bharat_report_layout.xml',
        'reports/loan_notice_reports.xml',
        'views/loan_views.xml',
        'data/loan_action_menu_cleanup.xml',
        'views/notice_line_views.xml',
        'views/dashboard_action.xml',
        'views/menus.xml',
        'data/hide_legacy_menus.xml',
    ],
    'assets': {
        'web.report_assets_pdf': [
            'bharatnyay_core/static/src/scss/bharat_report.scss',
        ],
        'web.assets_backend': [
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_slot_grid_field.scss',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_slot_grid_field.xml',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_slot_grid_field.js',
            'bharatnyay_core/static/src/dashboard/bharatnyay_dashboard.scss',
            'bharatnyay_core/static/src/loan_form/loan_form.scss',
            'bharatnyay_core/static/src/loan_form/notice_dialog_title.js',
            'bharatnyay_core/static/src/dashboard/bharatnyay_dashboard.xml',
            'bharatnyay_core/static/src/dashboard/bharatnyay_dashboard.js',
            'bharatnyay_core/static/src/dashboard/case_manager_dashboard.js',
            'bharatnyay_core/static/src/dashboard/arbitrator_dashboard.js',
            'bharatnyay_core/static/src/js/user_menus.js',
            'bharatnyay_core/static/src/list_view/list_primary_header.scss',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'pre_init_hook': 'pre_init_hook',
}
