{
    'name': 'BharatNyay Core',
    'version': '18.0.31.0.179',
    'icon': '/bharatnyay_core/static/description/icon.png',
    'summary': 'Loan portfolio aligned to Excel import template',
    'description': """
        Loan sheet model (`bharat.loan`) with masters for region, state, branch, location,
        product class, write-off and law firm. Import from spreadsheet via List ▸ Favorites ▸ Import Records.
    """,
    'category': 'Operations/Disputes',
    'author': 'BharatNyay Team',
    'depends': ['web', 'mail', 'calendar', 'account', 'account_payment', 'product', 'spiffy_theme_backend'],
    'data': [
        'security/bharatnyay_groups.xml',
        'security/bharatnyay_record_rules.xml',
        'security/ir.model.access.csv',
        'data/case_workflow_setup_data.xml',
        'data/post_office_status_data.xml',
        'data/postal_dispatch_backfill.xml',
        'data/billing_batch_sync.xml',
        'data/loan_sequence_data.xml',
        'data/loan_stage_data.xml',
        'data/loan_stage_award_update.xml',
        'data/milestone_scheduler_cron.xml',
        'data/case_vault_cron.xml',
        'data/bharat_pdf_config.xml',
        'data/notification_template_data.xml',
        'data/loan_milestone_data.xml',
        'data/arbitration_billing_products_data.xml',
        'views/master_views.xml',
        'views/res_company_views.xml',
        'views/res_users_views.xml',
        'views/notification_template_views.xml',
        'views/loan_notice_wizard_views.xml',
        'views/loan_notice_response_wizard_views.xml',
        'views/loan_postal_status_wizard_views.xml',
        'views/loan_milestone_advance_wizard_views.xml',
        'views/loan_pod_mark_done_wizard_views.xml',
        'views/loan_flow_simulation_views.xml',
        'views/bharat_operational_views.xml',
        'views/bharat_account_product_views.xml',
        'views/arbitration_billing_views.xml',
        'views/case_workflow_setup_views.xml',
        'views/case_vault_views.xml',
        'reports/arbitration_invoice_annexure_report.xml',
        'views/loan_hearing_wizard_views.xml',
        'views/loan_award_wizard_views.xml',
        'views/loan_assign_arbitrator_wizard_views.xml',
        'views/hearing_line_views.xml',
        'views/interim_order_views.xml',
        'views/award_document_views.xml',
        'data/bharat_report_paperformat.xml',
        'reports/bharat_report_layout.xml',
        'reports/loan_notice_reports.xml',
        'views/loan_views.xml',
        'data/loan_action_menu_cleanup.xml',
        'views/notice_line_views.xml',
        'views/dashboard_action.xml',
        'views/menus.xml',
        'data/case_workflow_setup_link.xml',
        'data/hide_legacy_menus.xml',
    ],
    'assets': {
        'web.report_assets_pdf': [
            'bharatnyay_core/static/src/scss/bharat_report.scss',
        ],
        'web.assets_backend': [
            'bharatnyay_core/static/src/scss/milestone_master.scss',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_slot_grid_field.scss',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_scheduler_field.scss',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_wizard.scss',
            'bharatnyay_core/static/src/interim_award_wizard/interim_award_wizard.scss',
            'bharatnyay_core/static/src/interim_order_form/interim_order_form.scss',
            'bharatnyay_core/static/src/milestone_advance_wizard/milestone_advance_wizard.scss',
            'bharatnyay_core/static/src/consolidated_invoice_wizard/consolidated_invoice_wizard.scss',
            'bharatnyay_core/static/src/flow_simulation/flow_simulation.scss',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_slot_grid_field.xml',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_slot_grid_field.js',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_scheduler_field.xml',
            'bharatnyay_core/static/src/hearing_slot_grid/hearing_scheduler_field.js',
            'bharatnyay_core/static/src/dashboard/bharatnyay_dashboard.scss',
            'bharatnyay_core/static/src/loan_form/loan_form.scss',
            'bharatnyay_core/static/src/loan_form/postal_delivery_cards_field.xml',
            'bharatnyay_core/static/src/loan_form/postal_delivery_cards_field.js',
            'bharatnyay_core/static/src/loan_form/notice_dialog_title.js',
            'bharatnyay_core/static/src/dashboard/bharatnyay_dashboard.xml',
            'bharatnyay_core/static/src/flow_simulation/flow_simulation.xml',
            'bharatnyay_core/static/src/flow_simulation/flow_simulation.js',
            'bharatnyay_core/static/src/dashboard/role_dashboard_templates.xml',
            'bharatnyay_core/static/src/dashboard/dashboard_helpers.js',
            'bharatnyay_core/static/src/dashboard/bharatnyay_dashboard.js',
            'bharatnyay_core/static/src/dashboard/case_manager_dashboard.js',
            'bharatnyay_core/static/src/dashboard/arbitrator_dashboard.js',
            'bharatnyay_core/static/src/js/user_menus.js',
            'bharatnyay_core/static/src/import_wizard/import_wizard.scss',
            'bharatnyay_core/static/src/case_vault/case_vault_list.scss',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'pre_init_hook': 'pre_init_hook',
    'post_init_hook': 'post_init_hook',
}
